name: Context
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      HEAD_REF: ${{ github.head_ref }}
    steps:
      - run: echo "${{ github.run_id }}"
      - run: echo "$HEAD_REF"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.repository_owner }}"
      - run: echo "${{ github.event.repository.name }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.actor }}"
