name: Parallel jobs
on: push
jobs: # jobsキーへh区数のジョブを定義すれば、並列に実行される
  firts:
    runs-on: ubuntu-latest
    steps:
        - run: sleep 10 && echo "First job"
  second:
    runs-on: ubuntu-latest
    steps:
        - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    steps:
        - run: sleep 10 && echo "Third job"
