name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${PASSWORD}" # ログの出力はマスクされる
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # ログの出力はマスクされない
