name: Static analysis
on:
    pull_request:
        paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
defaults: # デフォルトシェルを指定
    run:
        shell: bash # デフォルトシェルはもともとbashだが明示的に指定することでパイプ処理中のエラーを拾えるようになるのでデバッグしやすくなる
concurrency: # 自動キャンセル
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5 # タイムアウト
        steps:
            - uses: actions/checkout@v4
            - run: | # yamlの静的解析の実行
                docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
