name: Workflow with Approval
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job 1 completed."
  job2:
    runs-on: ubuntu-latest
    needs: job1
    environment:
      name: test
    steps:
      - name: Step 2
        run: echo "Job 2 completed."
  deploy:
    runs-on: ubuntu-latest
    needs: job2
    environment:
      name: test
    steps:
      - name: Deployment Step
        run: echo "Deployment approved and running."
